# Generated by Django 5.0.2 on 2024-02-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_contact_phone_remove_education_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='com_projects',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(upload_to='portfolio/media/portfolio/images/'),
        ),
    ]
