# Generated by Django 5.0.2 on 2024-02-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_resume'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education',
            new_name='Background',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
