# Generated by Django 5.0.2 on 2024-02-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_rename_service_skills_delete_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='percentage',
            field=models.IntegerField(),
        ),
    ]
