# Generated by Django 5.0.2 on 2024-02-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_skills_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='awards',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='coffee_cup',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='happy_customer',
            field=models.IntegerField(null=True),
        ),
    ]
