# Generated by Django 5.0.2 on 2024-02-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_person_awards_person_coffee_cup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='portfolio/media/portfolio/images/')),
            ],
        ),
    ]
