# Generated by Django 5.0.2 on 2024-02-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image1',
            field=models.ImageField(default=1, upload_to='portfolio/media/portfolio/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='image2',
            field=models.ImageField(default=1, upload_to='portfolio/media/portfolio/images/'),
            preserve_default=False,
        ),
    ]
