# Generated by Django 5.0.2 on 2024-02-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_person_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='document',
            field=models.FileField(default=1, upload_to='portfolio/media/portfolio/documents/'),
            preserve_default=False,
        ),
    ]
